name: Deliver Image
on:
  push:
    branches:
      - "!**"
      - master
      - main
      - trunk
concurrency: deliver-production
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build and Deploy with Cache'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Deploy Image
        id: all-tags
        # https://github.com/actions/github-script
        uses: actions/github-script@v6
        env:
          PROJECT_NAME: ${{ github.repository }}_${{ github.head_ref || github.ref_name }}
        with:
          github-token: ${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}
          script: |
            return github.rest.actions.createWorkflowDispatch({
              owner: 'kinetechsolutions',
              repo: 'magictent',
              workflow_id: 'deploy.yaml',
              ref: 'trunk',
              inputs: {
                'repo': context.repo.repo,
                'token': '${{ secrets.SVC_CLI_BOT_GITHUB_TOKEN }}',
                'project_name': '${{ env.PROJECT_NAME }}',
              }
            })
